### ISSUE TITLE
Come up with an idea for Tuesday/Thursday afternoon challenge

### ISSUE THREAD

**Issue by NataliaLKB** [gu-lseg/intro-to-programming#21]
@susiecoleman 's idea for robots is awesome! 

However we should discuss it and see if it is really the best thing

**Comment by susiecoleman** [comment]
I'm working on:
- programming line following 
- Checking we can get mindstorms software installed on education centre computers
- Can we program the robots in python
- Getting additional robots

**Comment by susiecoleman** [comment]
Scrapped Mindstorms idea.
Going to get them to go through http://codingbat.com/python and https://www.codewars.com/?language=python
