### ISSUE TITLE
Remove copyright

### ISSUE THREAD

**Issue by gtrufitt** [gu-lseg/intro-to-programming#22]
Can we properly open-source this as non-commercial attribution? https://creativecommons.org/licenses/by-nc/3.0/ Is Greg happy to be attributed as original author of this re-mixed course and removing the copyright notice to swap with link to licence? 

cc/ @NataliaLKB

**Comment by NataliaLKB** [comment]
I will send him an email this week!

**Comment by NataliaLKB** [comment]
@gtrufitt Greg has said we can properly opensource this!

**Comment by susiecoleman** [comment]
👍  yay

**Comment by gtrufitt** [comment]
Updated
