### ISSUE TITLE
Come up with guidance for mentors

### ISSUE THREAD

**Issue by NataliaLKB** [gu-lseg/intro-to-programming#24]
We should write some guidance for mentors who haven't mentored before.

Guidance can go here: https://docs.google.com/document/d/1LT4vpZvJA5dvkfeNT8nDCxQYsOnm6ygSd6Wd48xXFyY/edit

**Comment by NataliaLKB** [comment]
@susiecoleman @gtrufitt I have broken down the doc into two sections: 
"10 Tips for Mentors from the Workshop Team" and "Before the course we suggest you...". We need 4 more tips. Please edit/comment on the ones that are there.

**Comment by NataliaLKB** [comment]
Okay we have 10 tips! Feel free to add, edit and take away whatever you see fit 👍 . If you agree on these we can close this issue.

**Comment by susiecoleman** [comment]
👍 Looks good to me, great work

**Comment by gtrufitt** [comment]
This are really great @NataliaLKB :)

**Comment by NataliaLKB** [comment]
Great! Closing this then 😄
