### ISSUE TITLE
Arranging Lightning Talks

### ISSUE THREAD

**Issue by susiecoleman** [gu-lseg/intro-to-programming#31]
Check in with T how we are doing with finding lightning talk speakers.

**Comment by TormodMacLean** [comment]
Hi,

I've arranged the following talks:

Wednesday - Charlotte on working in UX and Jenny on the wide variety of types of development at the Guardian
Thursday - Rob Phillips on Getting in to Product and QA without a degree and Kate Whalen on Codebar

**Comment by susiecoleman** [comment]
👍

**Comment by NataliaLKB** [comment]
This has been done! 👍
