### ISSUE TITLE
Make slide to have on the projector at all times

### ISSUE THREAD

**Issue by NataliaLKB** [gu-lseg/intro-to-programming#39]
This will have:
- Link to the workshop
- Link to the cheatsheet
- Guidance for when people don't know something (ask a mentor!)
- Work in groups or on your own

**Comment by NataliaLKB** [comment]
@JonNorman @maxspencer @susiecoleman @TormodMacLean @gtrufitt 

What else am I missing? I can create this today.

**Comment by JonNorman** [comment]
Looks good to me!

**Comment by TormodMacLean** [comment]
This should include login details:

UN: masterclass1
PW: master

save location path: downloads/internet downloads

**Comment by NataliaLKB** [comment]
@TormodMacLean are we okay for these logins to be in this public repo, and on a public link? (the slide)

**Comment by TormodMacLean** [comment]
@NataliaLKB Sorry for the slow reply, super busy couple of hours. I'd forgotten that this repro was public - my bad. I've pulled them to be safe. These details are given to anyone who attends a masterclass that requires computer access so I don't think we should be too worried about sharing them - but does the slide need to be a public link? Cannot it not just be shared with people signed in with the a guardian email?

**Comment by NataliaLKB** [comment]
Well ideally it was going to just be an easily accessible webpage with links

**Comment by NataliaLKB** [comment]
I will just say "ask your mentor for logins"

**Comment by TormodMacLean** [comment]
Sounds good, whatever works best for you

**Comment by NataliaLKB** [comment]
First go at the slide here: http://nataliabaltazar.me/gu-workshop-welcome/. Short link is this: http://bit.do/guardianworkshop

Feel free to edit in this Repo: https://github.com/NataliaLKB/gu-workshop-welcome
