### ISSUE TITLE
Introduction to Towers of Hanoi

### ISSUE THREAD

**Issue by JonNorman** [gu-lseg/intro-to-programming#41]
The coding without computers task will be to solve the [Towers of Hanoi](https://en.wikipedia.org/wiki/Tower_of_Hanoi) problem, successively adding more rings up to 5.

@NataliaLKB is crafting together the pieces!

Once the task is completed, the following questions might be good to dive a bit deeper:
- How much harder was it to move 5 rather than 4?
- Is there a generalised version of your approach to deal with any number of rings?
- How long would it take with 64 rings if it took 1 second to move each ring?

**Comment by JonNorman** [comment]
### The towers of Hanoi!

**Challenge:** move the entire tower of rings from the rightmost pole to the leftmost pole.

**Rules:**
- only one ring can be moved at a time
- a ring cannot be placed on top of a smaller ring

#### Getting started

First try to complete the challenge with a tower just two rings high (this should be pretty easy!).

Next try completing the challenge again, but add another to the tower before you start!

#### Food for thought
1. How much harder is it to move a tower once you add an extra ring? How much longer does it take you?
2. Can you think of a general method for solving this challenge with any number of hoops?
3. How long do you think it would take you if you had a tower 64 rings high?

**Comment by NataliaLKB** [comment]
This looks great!

**Comment by NataliaLKB** [comment]
🎉
