### ISSUE TITLE
Notes from introduction and turtles run-through

### ISSUE THREAD

**Issue by gtrufitt** [gu-lseg/intro-to-programming#5]
I ran through the first two sections with Hayley - we discussed a few things as we went along but also skipped a couple of the excercises but it took around 1.5 hours to run through these two sections. I think that could probably end up at 2.5 hours which may or may not be too long if we've only got two days (there are 9 sections total but I am not sure if they'll be longer or shorter)...
## Appendix

There are some existing Appendix pages - link to them from the relevant points, we should also print these out as course notes as they will be useful. We should add another appendix that describes 'programming words' like syntax, parenthesis, terminal etc for the students to refer to. 
## General Notes
- Add a 'do this' to every part that requires something, like our 'to do' but helps differentiate from code snippets that require copying and ones that are just an example
- Make sure we are in the right folder - eg: run python in 'documents' and save
## Introduction
- 'What Python is' - is at the bottom of the intro - we should explain straight away a few basics like what Python is, what the course is and what we will learn.
- Explain what the terminal is and that you can't use a mouse
- When initally opening terminal, we want them to `cd` into the documents folder as they'll use it later in the tutorial - the appendix has some cmd line 101 (that probably needs updating to terminal)
- Short explanation of what a string is, short explanation of what a function is in the `print('hello')` section as it's the first time some people will be seeing this
- Excercise - try printing other words - change this to printing other strings, with spaces, with punctuation, listing any errors and seeing if you can fix them. They'll hit errors if they add unescaped punctuation and will begin to teach googling for errors.
### Errors
- On Errors - what different types of errors are there - syntaxError, nameError, indentationError (EOL)
### OOP
- Embolden 'Chair' and 'Person' types
- What is the difference between a method and function?
### Python
- What is 'syntax' (do we need appendix?)
- Difficult with 'language' and 'interpreter' - expand on what the difference is
- "Explain what happened when you wrote `print('hello')` - Using the Python language..."
### Language Goals
- Why is the code sample here? 'Our goal is to move from this to this' could be confusing _Lets discuss this_
- Change the values to further apart (100, 90 were near each other which implied some kind of relationship)
- "What is a code extract"
- This needs slightly more explanation for people who don't know what code looks like - add an example of how to call the function that is being defined
## Turtles

This is a good section, the interactivity is really good, turtles are fun!
- Explain that forward takes a number px input, left.right take degrees, shape and color take 'strings'
### Exercise
- Make bob a triangle so you can see which way he is going
- A square with two different colours exercise needs more explanation - an image of what should be there would help
## Creations
- What are parenthesis (type 'braces' after it) - refer to appendix
- Asking a question like 'what type of object is tess?' makes it clearer what we're actually asking of students
- type(tess) returns <class 'turtle.Turtle'> in terminal - we should update this and explain a bit more
## Methods
- Braces should have an appendix (parenthesis, braces, brackets)
## Code in files
- Add how to exit out of the python interpreter, back to the normal terminal window using cmd+d
- "Use sublimetext" - instead of using
- Move the experiment bit further down so not to confuse
- Make sure we are in the 'documents' folder (did they `cd` in the intro?)
- "We can comment our lines of code using #" - Explain why we would use a comment and what the python language does with them i.e: ignores them
- Change 'in cmd.exe' to 'in terminal'
- Remove the tilda and > from the front of the line call as it was confusing what it was (and will look different on each machine), I think the students just need to copy what is written.
- Explain `exitonclick()` a bit more, the questions ask why is it used but maybe add other examples of different type of exit
## Questions
- Question 1 - when would you use interactive vs files? Interactively is easier to see problems line by line, doing in a file is much quicker as can be edited.
## Shape Exercises

This could be extended for students who are ahead, so others can catch up - add a really cool example (like a spirograph):

![image](https://cloud.githubusercontent.com/assets/638051/16417846/66b57a46-3d3f-11e6-8e3c-7a308360b0a1.png)

cc/ @susiecoleman @maxspencer @NataliaLKB Just for your reference after running this with Hayley, I will make the changes to the actual course, but please comment on anything here.

**Comment by NataliaLKB** [comment]
@gtrufitt this is so great! I love these comments and agree with everything 👍
